name: Deploy Portfolio to S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NEXTJS_DIR: ${{ github.workspace }}/site
      FORECAST_API_BASE: ${{ secrets.FORECAST_API_BASE }}
      MONTE_API_BASE: ${{ secrets.MONTE_API_BASE }}
      PORTFOLIO_API_BASE: ${{ secrets.PORTFOLIO_API_BASE }}
      NEXT_PUBLIC_PORTFOLIO_API: ${{ secrets.PORTFOLIO_API_BASE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      DRY_RUN: false
      SKIP_NPM_CI: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install boto3 python-dotenv requests

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node.js deps
        run: npm ci
        working-directory: ./site

      - name: Build Next.js site
        run: npm run build
        working-directory: ./site

      - name: Export static site
        run: npx next export
        working-directory: ./site

      - name: Deploy via orchestrator
        run: python orchestrate_portfolio.py all
